---
title: "Lab 3 Warm Up"
output: html_document
date: "2023-01-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### plant height and weight vectors
```{r}
plant_height <- c(30.7, 37.6, 28.4, NA, 33.2)
```

```{r}
plant_mass <- c(4, 5.2, 3.7, NA, 4.6)
```


### build matrix
```{r}
plant_experiment <- c(plant_height, plant_mass)
```

```{r}
plant_matrix <- matrix(plant_experiment, nrow=5, byrow=F)
plant_matrix
```


### matrix labels
```{r}
plant_matrix_titles <- c("height", "mass")
plant_matrix_titles
```

```{r}
plant_names <- c("plant 1", "plant 2", "plant 3", "plant 4", "plant 5")
plant_names
```


```{r}
colnames(plant_matrix) <- plant_matrix_titles
rownames(plant_matrix) <- plant_names
```


### print matrix
```{r}
plant_matrix
```


### calculate column means
```{r}
plant_means <- colMeans(plant_matrix, na.rm=T)
plant_means
```


### add this column to the matrix
```{r}
plant_matrix_final <- rbind(plant_matrix, plant_means)
```


### print final version
```{r}
plant_matrix_final
```






