---
title: "Lab 14 Homework"
author: "Katie Ricketts"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
    keep_md: yes
---

## Lab 14 Binder
If you want to return to the binder, find the [repository and instructions here](https://github.com/hehouts/lab14_binder)

## Instructions
Answer the following questions in RMarkdown. Please embed all of your code and push your final work to your repository. Be sure to add your name to the author header above.



## Questions

*1. Look up 'Data Scientist' at https://www.bls.gov/. What degree is required for this career? Is it a growing occupation?  *

Data Scientists need to have at least a bachelor's degree in mathematics/statistics/computer science. The employment of data scientists is growing very fast.


*2. How would you describe your data science skills on a resume for a job application? Write a blurb that reflects the skills you have learned in this course.* 

I am able to code and do basic data analysis in R and RMarkdown, such as producing statistical summaries and graphs, as well as building simple apps that allow for more efficient analysis. 


*3. What are your current career interests, and how could your R skills support that career path? (hint: this might be good content for your LinkedIn profile ;)*

I would like to study the physiological effects of long-term space flight. My skills in R would allow me to perform data analysis on my own research results.


*4. What about this course has been the most difficult for you? What has been the most rewarding?*

The most difficult part of this course has been remembering all of the small details of the syntax, but building a cheat sheet with a summary of the commands we've learned has helped me a lot with that. The most rewarding parts have been when I figured out how to code something on my own after being stuck on it for a while.


*5. What do you wish you had known, or what skills do you wish you had, before taking this class.*

I already had a decent amount of basic coding skills before this class, but I wish I had a little bit more so that I could do even more with the skills we learned. However, I don't think any of these skills would have been necessary to taking this class.


*6. If we had 1 more lab in this class, what would you have liked to learn more about?*

I would have liked to learn more about 


*7. Now that you have (almost!) completed this course, do you plan to pursue further data or computer science skills? What do you plan to do?*

I would like to pursue more data science skills, but I'm not sure where or how I would do this. If there was a second course of this class that continued the material, I would definitely take it. 


*8. How important was working with a partner to your success in this class? If this class were transitioned to an online format, how do you think that would affect your understanding?*

Up until the group project started, I didn't have a strict partner in the class, but I did find it helpful to be able to ask the people sitting next to me questions if I missed something small or if Dr. Ledford and Hannah were busy. If this class was online I think it would be fine, but I definitely would not have gotten as much out of it. Doing group projects in a virtual class where you don't already have some familiarity with other people in the class would also be more difficult.


*9. Did you complete the class evaluation? Please complete the class evaluation using the link provided in the announcements. Your feedback is very important and we appreciate your time.*

I have not completed the course evaluation yet.


## Push your final code to GitHub!
Please be sure that you check the `keep md` file in the knit preferences. 
